# jobs:
# - job                       : BuildFunctionApps
#   displayName               : Build MicroCloud Licensing function app
#   steps:
#   - task                      : UseDotNet@2
#     displayName               : "Install .NET Core SDK"
#     inputs                    :
#       version                 : 10.x
#       performMultiLevelLookup : true
#       includePreviewVersions  : false

#   - task: DotNetCoreCLI@2
#     displayName: build apps for publishing
#     inputs:
#       command: 'publish'
#       publishWebProjects: false
#       projects: src/AzureFunction/src/*/*.Function.csproj
#       arguments: '--output publish_output --configuration Release'

#   # Publish the function app artifact
#   - task: PublishPipelineArtifact@1
#     displayName: Publish Function App
#     inputs:
#       targetPath          : '$(System.DefaultWorkingDirectory)/publish_output'
#       artifact            : 'functionApps'
#       publishLocation     : 'pipeline'

#   # Publish the Infrastructure artifacts.
#   - task                    : PublishPipelineArtifact@1
#     displayName             : Publish Infrastructure
#     inputs                  :
#       targetPath            : '$(System.DefaultWorkingDirectory)/src/AzureFunction/deploy'
#       artifact              : 'deploy'
#       publishLocation       : 'pipeline'


jobs:
- job: BuildFunctionApps
  displayName: Build MicroCloud Licensing function app
  steps:
  - task: UseDotNet@2
    displayName: "Install .NET Core SDK"
    inputs:
      version: 10.x
      performMultiLevelLookup: true

  - task: DotNetCoreCLI@2
    displayName: Publish App
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'src/AzureFunction/src/MicroCloud.Licensing.Function/MicroCloud.Licensing.Function.csproj' 
      arguments: '--output $(Build.ArtifactStagingDirectory)/publish_output --configuration Release -r win-x64 --self-contained true'
      zipAfterPublish: false

  - task: ArchiveFiles@2
    displayName: 'Zip published files'
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish_output/MicroCloud.Licensing.Function'
      includeRootFolder: false  
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/MicroCloud.Licensing.Function.zip'
      replaceExistingArchive: true

  # Publish the ZIP file
  - task: PublishPipelineArtifact@1
    displayName: Publish Function App Zip
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/MicroCloud.Licensing.Function.zip'
      artifact: 'functionApps'
      publishLocation: 'pipeline'

  # Publish the Bicep files
  - task: PublishPipelineArtifact@1
    displayName: Publish Infrastructure
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/src/AzureFunction/deploy'
      artifact: 'deploy'
      publishLocation: 'pipeline'